# Generated by Django 4.1.3 on 2023-01-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_stain_tissue_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
    ]
