# Generated by Django 4.1.3 on 2023-01-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='image',
            new_name='label',
        ),
        migrations.AddField(
            model_name='slide',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
