# Generated by Django 4.1.3 on 2023-01-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_gender_rename_image_slide_label_slide_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='age',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.gender'),
        ),
    ]
