# Generated by Django 4.1.3 on 2023-01-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_title_alter_slide_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.title'),
            preserve_default=False,
        ),
    ]
