# Generated by Django 4.1.3 on 2023-02-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissue',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tissue', to='database.system'),
            preserve_default=False,
        ),
    ]
