# Generated by Django 4.1.3 on 2023-02-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_tissue_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WHO_diagnosis', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tissue',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.system'),
        ),
    ]
