# Generated by Django 4.1.3 on 2023-02-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_diagnosis_alter_tissue_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.diagnosis'),
        ),
    ]
