# Generated by Django 4.1.3 on 2023-02-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup',
            field=models.BooleanField(default=False),
        ),
    ]
